resources:
  - ../../base

patches:
  - target:
      kind: HorizontalPodAutoscaler
      name: demo-webapp-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2
      - op: replace
        path: /spec/maxReplicas
        value: 4
      - op: replace
        path: /spec/metrics/0/resource/target/averageUtilization
        value: 60
  - target:
      kind: Ingress
      name: demo-webapp-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: pre.demo-webapp.local
