# File: nginx/overlays/v2/kustomization.yaml
resources:
  - ../../base
configMapGenerator:
  - name: nginx-html
    files:
      - index.html
vars:
  - name: INGRESS_HOST
    objref:
      kind: Ingress
      name: nginx-ingress
    fieldref:
      fieldpath: spec.rules[0].host
      
patchesStrategicMerge:
  - |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: nginx-ingress
    spec:
      rules:
      - host: v2.nginx.test