# File: nginx/overlays/v1/kustomization.yaml
resources:
  - ../../base
configMapGenerator:
  - name: nginx-html
    behavior: merge
    files:
      - index.html
    options:
      labels:
        version: v2
patches:
  - target:
      kind: Ingress
      name: nginx-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: v2.nginx.test
  - target:
      kind: Deployment
      name: nginx-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: ConfigMap
      name: nginx-html
    patch: |-
      - op: replace
        path: /data/index.html
        value: |-
          $(sed -e 's/$${VERSION}/v2 (Production)/g' < index.html)