resources:
  - ../../base
configMapGenerator:
  - name: nginx-html
    files:
      - index.html
patches:
  - target:
      kind: Ingress
      name: nginx-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: v2.nginx.test