# File: nginx/overlays/v2/kustomization.yaml
resources:
  - ../../base
configMapGenerator:
  - name: nginx-html
    behavior: merge
    files:
      - ../../base/src/index.html
    options:
      labels:
        version: v2
patches:
  - target:
      kind: Ingress
      name: nginx-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: v2.nginx.test
  - target:
      kind: ConfigMap
      name: nginx-html
    patch: |-
      - op: replace
        path: /data/index.html
        value: |-
          $(sed -e 's/$${VERSION}/v2 (Test)/g' < ../../base/index.html)