apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-v1
data:
  index.html: |
    <html>
    <head><title>NGINX Version 1</title></head>
    <body>
    <h1>Welcome to NGINX - Version 1</h1>
    </body>
    </html>