apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-v1  # Cambia a nginx-v2 si deseas desplegar la versión 2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort