resources:
  - ../../base

patches:
  - target:
      kind: HorizontalPodAutoscaler
      name: demo-webapp-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 3
      - op: replace
        path: /spec/maxReplicas
        value: 10
      - op: replace
        path: /spec/metrics/0/resource/target/averageUtilization
        value: 50

  - target:
      kind: Deployment
      name: demo-webapp
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3

  - target:
      kind: Ingress
      name: demo-webapp-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: demo-webapp.com