apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: VERSION
          value: "Base Version"
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
        - mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
          name: nginx-config
      volumes:
      - name: html
        configMap:
          name: nginx-html
      - name: nginx-config
        configMap:
          name: nginx-config