# File: nginx/overlays/v1/kustomization.yaml
resources:
  - ../../base
configMapGenerator:
  - name: nginx-html
    behavior: merge
    files:
      - index.html
    options:
      labels:
        version: dev
patches:
  - target:
      kind: Ingress
      name: nginx-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.nginx.test
  - target:
      kind: Deployment
      name: nginx-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1