apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-v1
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome to NGINX v1</title>
    </head>
    <body>
        <h1>Welcome to NGINX version 1</h1>
        <p>This is the v1 configuration of the web server.</p>
    </body>
    </html>