resources:
  - ../../base/deployment.yaml  
  - ../../base/service.yaml

configMapGenerator:
  - name: nginx-html
    files:
      - index.html=configmap.yaml

patchesStrategicMerge:
  - configmap.yaml