# File: nginx/overlays/v1/kustomization.yaml
resources:
  - ../../base
configMapGenerator:
  - name: nginx-html
    files:
      - index.html
patches:
  - target:
      kind: Ingress
      name: nginx-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: v1.nginx.test
  - target:
      kind: Deployment
      name: nginx-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2