resources:
  - ../../base
configMapGenerator:
  - name: nginx-html
    behavior: merge
    files:
      - ../../base/src/index.html
    options:
      labels:
        version: v1
patches:
  - target:
      kind: Ingress
      name: nginx-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: v1.nginx.test
  - target:
      kind: Deployment
      name: nginx-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "v1"